### ISSUE TITLE
APK out of date

### ISSUE THREAD

**Issue by elliotcm** [todotxt/todo.txt-android#320]
Hi there,

It looks like the APK downloads linked from the README (https://github.com/ginatrapani/todo.txt-touch/downloads) are getting quite old now.

Is there a reason you're not uploading recent versions?  Should we be compiling from source?

All the best,
Elliot

**Comment by mbnoimi** [comment]
Sorry for bringing it from the past:
https://github.com/blog/1547-release-your-software
You can publish the apk in release section.
