### ISSUE TITLE
Clean up codebase by enforcing consistent code style guidelines

### ISSUE THREAD

**Issue by ginatrapani** [todotxt/todo.txt-android#396]
Up until now Todo.txt has been written by dozens of programmers over several years, and on code review I didn't enforce any standard code style guidelines, which means our code isn't as readable or clean as it should be.

Standard code style makes code more readable and easier to maintain, so it's even more important for open source projects, which have multiple developers coming and going over time.

Let's start cleaning up our code to adhere to these published AOSP guidelines:

http://source.android.com/source/code-style.html

A few additional guidelines I'd like us to follow:
- Name string resources using `all_lower_case_underscore_style`
- Name all methods using `camelCaseStartingWithLowercaseLetter`. Methods that return booleans should start with is or has, ie, `isThisCaseTrue` or `hasThisInformation`

**Comment by evanp** [comment]
I just ran the code-reformatting tool in Android Studio and pushed it to master. Seems like it gets most of these changes. I think it makes sense to close this issue and open specific issues for specific formatting problems.
