### ISSUE TITLE
Compiling in Intelli J

### ISSUE THREAD

**Issue by simao** [todotxt/todo.txt-android#443]
Hello,

I am trying to compile todo.txt in Intelli J and I am running into some problems.

Basically some class names defined in styles.xml are not defined anywhere, for example:

Theme.Sherlock.Light.DarkActionBar and Widget.Sherlock.Light.ActionBar.Solid.Inverse 

I assume this is because ActionPullToRefresh is not being built as a dependency and included in the main module, which I image happens with the other dependencies as well.

Anyone has any tips on setting this up on Intellij? How to make these dependencies compile?

Thanks

**Comment by karbassi** [comment]
Related to #369
