### ISSUE TITLE
Recent Versions

### ISSUE THREAD

**Issue by JStyle21** [todotxt/todo.txt-android#465]
Hi,

First of all let me say this was a nice project (the choice to use dropbox is understandable but poor).
What this is really lacking is support for gradle, running it with gradlew rather with android studio or having build instructions would have been much easier (not everyone can fine the simple dropbox xml file instructions).

Also it now complains about strings.xml having 2 strings with the name done, i guess this is a bug now so i changed the name.

Thanks.
J

**Comment by ginatrapani** [comment]
Thanks! Pull requests welcome!

**Comment by rafid059** [comment]
@ginatrapani There are two strings named "done" in [strings.xml](https://github.com/ginatrapani/todo.txt-android/blob/master/res/values/strings.xml). Can you please tell which one is safe to delete?

**Comment by karbassi** [comment]
Duplicates #369
