### ISSUE TITLE
Dropbox V1 API will shut down 6/28/2017.

### ISSUE THREAD

**Issue by mpcjanssen** [todotxt/todo.txt-android#469]
The dropbox v1 API will be shut down on 6/28/2017. (https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) This means that any app which uses the old V1 API will stop to work.

For simpletask I am already looking into this (https://github.com/mpcjanssen/simpletask-android/issues/470) and the migration to V2 is certainly not trivial.

**Comment by felixkm** [comment]
This library might help you with that: https://github.com/CloudRail/cloudrail-si-ios-sdk
Supports Dropbox v2 API plus Google Drive, OneDrive and Box via the same API.

**Comment by forty9er** [comment]
It will be a great shame if the app stops working - this is still my favourite Todo app. I've never worked on an Android app and thought I'd have a go at updating this to use the v2 API but I couldn't get the code to build in either the latest IntelliJ or Android Studio. It's a shame the project has been abandoned, if only it had been updated to use Gradle I might have had half a chance.

**Comment by mpcjanssen** [comment]
@forty9er I don't understand what you mean. The project is not abandoned and it is using gradle. What problems do you have with building it?

**Comment by forty9er** [comment]
@mpcjanssen OK - I must be mistaken. I cloned the project and tried to build and run tests in both IntelliJ (which I use every day) and Android Studio (which I'm totally unfamiliar with, aside from its similarities to IntelliJ). I didn't have any success either way but I can't remember now what the errors were. I'll give it another shot and report back. I'm used to using projects which use the Gradle Wrapper, and I couldn't see a build.gradle file anywhere in the project so I assumed it wasn't built using Gradle at all.

**Comment by mpcjanssen** [comment]
@forty9er  it does use the gradle wrapper and the build.gradle file is in the app folder

**Comment by forty9er** [comment]
Hi @mpcjanssen, I just thought I'd take another look at this. I cloned the repo again, `cd` in to the root directory and then ran `find . | grep build.gradle` from the command line. The only `build.gradle` file I can find is in `ActionBar-PullToRefresh`:

 `./dependencies/ActionBar-PullToRefresh-e8e6d2b58c/extras/actionbarsherlock/build.gradle
./dependencies/ActionBar-PullToRefresh-e8e6d2b58c/library/build.gradle`

Perhaps I'm missing something or am just unfamiliar with Android Gradle projects. I'm not sure which folder is the 'app' folder you speak of. In my experience (of web apps), the `build.gradle` file is always in the root directory. Happy to be wrong on this, I just don't know how to get started.

**Comment by mpcjanssen** [comment]
@forty9er I am not sure exactly what is causing this, but actionbar pull to refresh hasn't been a dependency in ages. This was before the move to gradle. Are you on the master branch? For me this gives:

```
 simpletask-android]$ find . | grep build.gradle
./app/build.gradle
./extras/daogenerator/build.gradle
./extras/simpletask-key/build.gradle
```

**Comment by mpcjanssen** [comment]
@forty9er 
Me smacks forehead. I didn;t realize this is the `todo.txt` issue I was commenting on. Ignore my remarks.

**Comment by alister** [comment]
Dropbox: September 28, 2017: API v1 endpoints are turned off

Todotxt-android is now failing to sync with Dropbox, and there has been no apparent update since v2.2, several years ago.

**Comment by sarana1** [comment]
Hi. Love todo.txt. I have an old gingerbread phone I still use as a backup. Simpletask will not run on it, but the original Todo.txt app will, but not now with the new DB API. I'm not a developer, or I would try it myself, but I would love it if someone would try to get the original Todo.txt app working again! Thanks to mpcjanssen for all your work!

**Comment by rlpowell** [comment]
Is there, in fact, a developer who can push a new version?  I could probably figure out how to fix the code, but I'm not going to bother if it's not going to get released.

**Comment by inkarkat** [comment]
@rlpowell The todotxt organization has recently taken over the projects, and its main owner (karbassi) has received the API keys for releasing a new version from Gina (I think). Also, Gina is still around.

**Comment by jsb111** [comment]
Good to know there is some hope for todo.txt. I have been using it for several years now and I got a copy for my wife too. The failure of synchronization has been a concern the last few days

**Comment by Surf2Sun** [comment]
Does anyone know the location todo.txt on the android app I would like to manual sync the file and use it offline until a new version comes out? I had a quick look and it wasn't anywhere obvious

**Comment by jsb111** [comment]
/storage/emulated/0/Android/data/com.dropbox.android/files/u48282343/scratch/todo

This what I found .
But Android may many different paths to the same file. I dont like the
directory structure in android
Steve

On Oct 7, 2017 1:37 PM, "Surf2Sun" <notifications@github.com> wrote:

Does anyone know the location todo.txt on the android app I would like to
manual sync the file and use it offline until a new version comes out? I
had a quick look and it wasn't anywhere obvious

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/todotxt/todo.txt-android/issues/469#issuecomment-334964212>,
or mute the thread

**Comment by sarana1** [comment]
You can also just use something like Dropsync on your device and have it sync with dropbox and a local folder, although Dropsync has not updated their API for older versions of Android. There are other apps like Dropsync that might work.

**Comment by Surf2Sun** [comment]
What about interim release? Where the app syncs with a file located on the normally accessible phones files system? i.e. implement an adapter for the existing drop box api that just reads a flle straight off the file system? 
If the new version going to be more than a few weeks, I would be happy to make that change.

**Comment by karbassi** [comment]
Related to #481 and #482

**Comment by forkmantis** [comment]
I did not think of using DropSync.  I ended up discovering SImpleTask for Android.  I'm liking it enough I'm not sure if I'll switch back to todotxt when it is updated.
