### ISSUE TITLE
Periodic sync not working

### ISSUE THREAD

**Issue by andreasmjg** [todotxt/todo.txt-android#470]
For some reason, periodic sync isn't working for me even though I've set it to sync every 15 minutes in the app. It's annoying because I do a lot of task overview in the tube and only notice it didn't sync last night's changes when I'm down there without reception.

When I start the app manually it syncs ok, but since no sync diff at the task level, only at file level. So I must lose either Dropbox content or phone content.

Todo.txt v2.2
Device LG-H815
Android 6.0 (build MRA58K)

**Comment by karbassi** [comment]
Related to #481
