### ISSUE TITLE
App doesn't sync with Dropbox

### ISSUE THREAD

**Issue by daviddjia** [todotxt/todo.txt-android#484]
Hey Gina, 

I've been using todo.txt for a while now with no problems. But recently, I noticed that I can't sync anymore from my phone. The When I go to "File location", it says "Failed to load folder list from Dropbox and I can't select a location. I have tried to log out and log back into Dropbox, and I have also tried reinstalling the app. 

I have a Galaxy S6, Android version 7.0. I can provide more details if you need them. 

Thanks!

**Comment by Elangco** [comment]
Would it be possible to make a version that does not depend on Dropbox?

Like just select any folder anywhere and let somebody else (maybe Dropbox, maybe Google drive, maybe pidgins carrying floppy disks) manage the syncing?

**Comment by derteta** [comment]
Seeing this also. I haven't checked, but if the app is using the Dropbox API 1.0, the cause is here:
https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/

I agree with @Elangco , making the app independent of the cloud service would be nice.

**Comment by karbassi** [comment]
There is discussion and forward movement on this in #482

**Comment by karbassi** [comment]
Duplicates #481
