### ISSUE TITLE
Not available in my country

### ISSUE THREAD

**Issue by 12people** [todotxt/todo.txt-android#497]
Why is this app not available in the Czech Republic?

**Comment by johannesgunnar** [comment]
I am guessing it's the same reason as in #492

**Comment by 12people** [comment]
Yup :)

**Comment by ViraCamilla** [comment]
I hope they will find someone to do the neccessary changes for the [Dropbox v3 API](https://www.dropbox.com/developers). 
In the meantime, I will use [Scarlet Notes](https://play.google.com/store/apps/details?id=com.bijoysingh.quicknote.pro) by @BijoySingh.
