### ISSUE TITLE
Restore unit tests

### ISSUE THREAD

**Issue by evanp** [todotxt/todo.txt-android#502]
When we moved to Gradle, the unit tests disappeared. We need to add them back into the project so we can make changes; this is especially important for testing that updates to the Dropbox API work.

**Comment by dae3** [comment]
Working on this one now

**Comment by dae3** [comment]
OK, unit tests are back and running at dae3/todo.txt-android@8758910ceea96c1a3a28f4e10f76bbad2e5ea532.

A number are failing because of test environment problems, mostly seems to be missing mocks for Android system bits.

I'll start working through but it'd be good to get some more eyes on this.

**Comment by dae3** [comment]
Here's what needs work:
- [ ] Mock Environment.getExternalStorageDirectory in DropboxFileUploaderTest
- [ ] TodoApplicationTest is failing trying to call setUp on the superclass (ApplicationTestCase)
- [ ] DropboxFileDownloaderTest: JUnit is looking for a TestCase(String) or TestCase() constructor
- [ ] PhoneNumberParserTest failing the test_with*German* tests; looks like a genuine test failure
- [ ] TestBagImplTest is trying to call getContext() on AndroidTestCase
- [ ] RelativeDateTest is trying to call runTest on InstrumentationTestCase
- [ ] TodoTxtTouchTest, JUnit's not running any of the tests "No tests found in com.todotxt.todotxttouch.test.TodoTxtTouchTest"

I'm more comfortable with Junit 4, I'll need to take some time understanding how this JUnit 3 test suite's structured.

If anyone has a the output of a test run from the pre-Gradle build that'd be great too, to distinguish between genuine test failures and test environment breakage.
